// Diccionario de traducciones ES/EN. Clave plana (namespace.subkey) para
// simplicidad. El español es la fuente de verdad (UI venezolana); el inglés
// sirve a ONGs internacionales y migrantes.
//
// Convención de claves: <pagina>.<elemento>. Variables con {nombre}.

export type Lang = 'es' | 'en';

export const dict = {
  es: {
    // --- nav / layout ---
    'nav.report': 'Reportar',
    'nav.map': 'Mapa',
    'nav.search': 'Buscar',
    'nav.safe': 'Estoy bien',
    'nav.phones': 'Teléfonos',
    'nav.volunteers': 'Voluntarios',
    'footer.tagline': 'proyecto solidario · datos abiertos · ayuda mutua',

    // --- home ---
    'home.kicker': '● Respuesta de emergencia',
    'home.title': 'Cuando cada minuto cuenta,\nla ayuda llega más rápido.',
    'home.lead': 'Reporta una emergencia con tu ubicación, encuentra a tus seres queridos y coordina el rescate. Funciona aunque la señal sea débil.',
    'home.cta': '🆘 Pedir ayuda ahora',
    'home.card.map.title': 'Mapa de SOS',
    'home.card.map.desc': 'Voluntarios y rescatistas ven dónde se necesita ayuda, en vivo.',
    'home.card.search.title': 'Buscar personas',
    'home.card.search.desc': 'Busca o reporta a alguien desaparecido tras el sismo.',
    'home.card.safe.title': 'Estoy bien',
    'home.card.safe.desc': 'Avisa a tu familia que estás a salvo en segundos.',
    'home.card.sos.title': 'Reportar SOS',
    'home.card.sos.desc': 'Médico, rescate, atrapado, agua o comida.',
    'home.card.phones.title': 'Teléfonos de emergencia',
    'home.card.phones.desc': 'Bomberos, ambulancias y rescate. Toca para llamar.',

    // --- tipos de emergencia ---
    'type.medical': '🩺 Médico / herido',
    'type.rescue': '🚒 Rescate',
    'type.trapped': '🏚️ Atrapado / colapso',
    'type.water_food': '💧 Agua / comida',
    'type.other': '❓ Otro',
    'type.medical.short': '🩺 Médico',
    'type.rescue.short': '🚒 Rescate',
    'type.trapped.short': '🏚️ Atrapado',
    'type.water_food.short': '💧 Agua/comida',
    'type.other.short': '❓ Otro',

    // --- estados ---
    'status.pending': 'pendiente',
    'status.dispatched': 'en camino',
    'status.resolved': 'resuelto',
    'status.false_report': 'descartado',
    'status.pending.long': 'Pendiente — esperando ayuda',
    'status.dispatched.long': 'En camino — la ayuda va para allá',
    'status.resolved.long': 'Resuelto — atendido',
    'status.false_report.long': 'Descartado',

    // --- SOS ---
    'sos.kicker': '● Emergencia',
    'sos.title': 'Pedir ayuda',
    'sos.lead': 'Tu reporte aparecerá en el mapa para que voluntarios y rescatistas te encuentren.',
    'sos.queued.count': '⏳ {n} reporte(s) guardado(s) sin conexión. Se enviarán al volver la red.',
    'sos.field.type': 'Tipo de emergencia',
    'sos.field.what': '¿Qué ocurre? (cuántas personas, heridos, detalles)',
    'sos.field.what.ph': 'Ej: 4 personas atrapadas en planta baja, una herida.',
    'sos.field.contact': 'Contacto (opcional)',
    'sos.field.contact.ph': 'Nombre y/o teléfono',
    'sos.loc.title': '📍 Ubicación',
    'sos.loc.coords': 'Lat {lat}, Lng {lng}',
    'sos.loc.getting': 'Obteniendo ubicación…',
    'sos.loc.useGps': 'Usar mi ubicación GPS',
    'sos.loc.manual': '¿Dónde estás? (referencia escrita)',
    'sos.loc.manual.ph': 'Ej: Av. Bolívar, edificio azul frente a la plaza, piso 3.',
    'sos.err.noGps': 'No pudimos obtener tu ubicación por GPS. Puedes escribir una referencia y enviar igual.',
    'sos.err.noLocAtAll': 'Comparte tu ubicación GPS o escribe una referencia de dónde estás.',
    'sos.err.noSupport': 'Tu dispositivo no soporta geolocalización.',
    'sos.err.captcha': 'Completa la verificación anti-spam para enviar.',
    'sos.submit': 'Enviar SOS',
    'sos.submitting': 'Enviando…',
    'sos.err.generic': 'No se pudo enviar. Intenta de nuevo.',
    'sos.ok': '✅ SOS enviado. Mantente a salvo, vienen en camino.',
    'sos.queued': '⏳ Sin conexión: tu SOS quedó guardado y se enviará automáticamente.',
    'sos.ref.prefix': '📍 Referencia',
    'sos.share.title': 'Comparte este enlace con tu familia para que sigan el estado:',
    'sos.share.copy': '📋 Copiar enlace',
    'sos.share.copied': '✓ Copiado',
    'sos.share.whatsapp': '💬 WhatsApp',
    'sos.share.waText': 'Sigue mi SOS: {url}',

    // --- mapa ---
    'map.kicker': '● Coordinación en vivo',
    'map.title': 'Mapa de SOS',
    'map.lead': 'Los reportes aparecen en tiempo real. Voluntarios: coordínense por zona y prioridad.',
    'map.legend.pending': 'Pendiente',
    'map.legend.dispatched': 'En camino',
    'map.legend.resolved': 'Resuelto',
    'map.filter.all': 'Todos ({n})',
    'map.loading': 'Cargando mapa…',
    'map.error': '⚠️ No pudimos cargar el mapa. Reintentando…',
    'map.noCoords': '{n} reporte(s) sin GPS no aparecen en el mapa (ver lista de voluntarios).',
    'map.noDesc': 'Sin descripción',

    // --- buscar ---
    'search.kicker': '● Personas',
    'search.title': 'Buscar personas',
    'search.lead': 'Busca por nombre o reporta a alguien desaparecido.',
    'search.input.ph': 'Nombre o cédula…',
    'search.btn': 'Buscar',
    'search.report.open': '➕ Reportar desaparecido',
    'search.report.close': 'Cerrar',
    'search.field.name': 'Nombre completo',
    'search.field.doc': 'Cédula / DNI (opcional)',
    'search.field.doc.ph': 'V-12345678',
    'search.field.lastSeen': 'Última ubicación conocida',
    'search.field.desc': 'Señas (edad, ropa, etc.)',
    'search.field.contact': 'Tu contacto',
    'search.field.editorDoc': 'Tu cédula de reportante (opcional) — necesaria para editar luego',
    'search.field.editorDoc.ph': 'Tu cédula, p. ej. V-12345678',
    'search.field.photo': 'Foto (opcional) — ayuda a identificar',
    'search.photo.preview': 'Vista previa',
    'search.submit': 'Reportar',
    'search.uploading': 'Subiendo foto…',
    'search.ok': '✅ Reporte registrado.',
    'search.queued': '⏳ Sin conexión: se enviará al volver la red.',
    'search.err.captcha': 'Completa la verificación anti-spam para enviar.',
    'search.noResults': 'Sin resultados.',
    'search.edit': '✏️ Editar',
    'person.status.missing': 'desaparecido',
    'person.status.safe': 'seguro',
    'person.status.found': 'encontrado',
    'person.status.found_pending': 'por confirmar',

    // --- estoy bien ---
    'safe.kicker': '● A salvo',
    'safe.title': 'Estoy bien',
    'safe.lead': 'Avisa que estás a salvo. Aparecerás como “seguro” cuando alguien te busque.',
    'safe.field.name': 'Tu nombre completo',
    'safe.field.doc': 'Cédula / DNI (opcional) — te servirá para editar luego',
    'safe.field.doc.ph': 'V-12345678',
    'safe.field.where': '¿Dónde estás? (refugio, zona)',
    'safe.field.contact': 'Contacto (opcional)',
    'safe.field.photo': 'Foto (opcional) — ayuda a que te reconozcan',
    'safe.submit': 'Avisar que estoy bien',
    'safe.uploading': 'Subiendo foto…',
    'safe.ok': '✅ Registrado. Tus seres queridos podrán encontrarte.',
    'safe.queued': '⏳ Sin conexión: se enviará al volver la red.',
    'safe.err.captcha': 'Completa la verificación anti-spam para enviar.',
    'safe.reportedBy': 'la propia persona',

    // --- emergencias ---
    'emerg.kicker': '● Directorio',
    'emerg.title': 'Números de emergencia',
    'emerg.lead': 'Toca un número para llamar directamente. Si es una emergencia que puedes geolocalizar, repórtala también en el mapa.',
    'emerg.national': 'Nacional',
    'emerg.rescue': 'Rescate y ambulancias',
    'emerg.outdated': '¿Falta un número de tu zona o alguno cambió? Avísanos para mantenerlo al día.',

    // --- seguimiento /r/[id] ---
    'track.kicker': '● Seguimiento de SOS',
    'track.loading': 'Cargando seguimiento…',
    'track.notfound.title': 'Reporte no encontrado',
    'track.notfound.lead': 'Este enlace no corresponde a ningún reporte activo. Puede que haya sido resuelto y archivado, o que el enlace esté mal copiado.',
    'track.notfound.home': 'Ir al inicio',
    'track.reportedAt': 'Reportado el {date}',
    'track.autoUpdate': 'Esta página se actualiza sola. Mantenla abierta para ver el estado en vivo.',
    'track.viewMap': 'Ver mapa',
    'track.reportAnother': 'Reportar otro SOS',

    // --- voluntarios (login/guard) ---
    'vol.kicker': '● Voluntarios',
    'vol.title': 'Panel de coordinación',
    'vol.loading': 'Cargando…',
    'vol.access.kicker': '● Acceso voluntarios',
    'vol.access.lead': 'Acceso solo para voluntarios autorizados. Inicia sesión con tu cuenta de Google.',
    'vol.google': 'Continuar con Google',
    'vol.noperm.kicker': '● Acceso restringido',
    'vol.noperm.title': 'Sin permiso',
    'vol.noperm.lead': 'Tu cuenta ({email}) no está autorizada como voluntario. Contacta a un coordinador para que te dé de alta.',
    'vol.signout': 'Cerrar sesión',

    // --- admin ---
    'admin.kicker': '● Administración',
    'admin.title': 'Gestión de voluntarios',
    'admin.loading': 'Cargando…',
    'admin.norole.title': 'Acceso restringido',
    'admin.norole.lead': 'Inicia sesión desde el panel de voluntarios.',
    'admin.goVol': 'Ir a voluntarios',
    'admin.noperm.title': 'Sin permiso',
    'admin.noperm.lead': 'Tu cuenta ({email}) no es administradora. Esta sección es solo para coordinadores.',
    'admin.backReports': '← Panel de reportes',
    'admin.lead': 'Aprueba solicitudes y administra el equipo de voluntarios.',

    // --- volunteer panel ---
    'vpanel.kicker': '● Coordinación',
    'vpanel.title': 'Panel de voluntarios',
    'vpanel.admin': '★ Gestión de voluntarios',
    'vpanel.signout': 'Salir ({email})',
    'vpanel.summary': '{pending} pendientes · {dispatched} en camino · {resolved} resueltos',
    'vpanel.filter.active': 'Activos',
    'vpanel.filter.pending': 'Pendientes',
    'vpanel.filter.dispatched': 'En camino',
    'vpanel.filter.resolved': 'Resueltos',
    'vpanel.filter.false_report': 'Falsos',
    'vpanel.loading': 'Cargando reportes…',
    'vpanel.empty': 'No hay reportes en esta vista.',
    'vpanel.viewMap': 'ver mapa',
    'vpanel.noGps': '📍 Sin GPS — ver referencia en la descripción',
    'vpanel.action.dispatch': '→ En camino',
    'vpanel.action.resolve': '✓ Resuelto',
    'vpanel.action.reopen': '↺ Reabrir',
    'vpanel.action.false': '⚑ Falso',
    'vpanel.tab.reports': 'Reportes SOS',
    'vpanel.tab.persons': 'Personas',

    // --- confirmaciones (modales) ---
    'confirm.cancel': 'Cancelar',
    'confirm.report.false.title': '¿Marcar como reporte falso?',
    'confirm.report.false.msg': 'Desaparecerá del mapa público. Podrás reabrirlo después.',
    'confirm.report.false.ok': 'Sí, marcar como falso',
    'confirm.report.resolve.title': '¿Marcar como resuelto?',
    'confirm.report.resolve.msg': 'Se mostrará como atendido en el mapa.',
    'confirm.report.resolve.ok': 'Sí, resuelto',
    'confirm.person.found.title': '¿Confirmar que la persona fue encontrada?',
    'confirm.person.found.msg': 'Se marcará como encontrada. Asegúrate de haberlo verificado.',
    'confirm.person.found.ok': 'Sí, encontrada',
    'confirm.person.reject.title': '¿Rechazar el aviso de aparición?',
    'confirm.person.reject.msg': 'Volverá a marcarse como desaparecida.',
    'confirm.person.reject.ok': 'Sí, sigue desaparecida',
    'confirm.person.safe.title': '¿Marcar como a salvo?',
    'confirm.person.safe.msg': 'Se mostrará como segura.',
    'confirm.person.safe.ok': 'Sí, a salvo',
    'confirm.claim.title': '¿Avisar que crees que apareció?',
    'confirm.claim.msg': 'Un voluntario lo verificará antes de marcarla como encontrada.',
    'confirm.claim.ok': 'Sí, avisar',

    // --- persons panel (voluntarios) ---
    'ppanel.summary': '{missing} desaparecidos · {safe} a salvo · {found} encontrados',
    'ppanel.filter.all': 'Todas',
    'ppanel.filter.missing': 'Desaparecidos',
    'ppanel.filter.safe': 'A salvo',
    'ppanel.filter.found': 'Encontrados',
    'ppanel.filter.found_pending': 'Por confirmar',
    'ppanel.loading': 'Cargando personas…',
    'ppanel.empty': 'No hay personas en esta vista.',
    'ppanel.reportedBy': 'Reportó: {who}',
    'ppanel.claimNote': '🙌 El reportante cree que apareció. Confirma o rechaza.',
    'ppanel.action.missing': '🔎 Desaparecido',
    'ppanel.action.safe': '✅ A salvo',
    'ppanel.action.found': '🙌 Encontrado',
    'ppanel.action.confirmFound': '✓ Confirmar encontrado',
    'ppanel.action.reject': '✗ No apareció',

    // --- admin panel ---
    'apanel.pending': 'Solicitudes pendientes',
    'apanel.pending.count': 'Solicitudes pendientes ({n})',
    'apanel.loading': 'Cargando…',
    'apanel.pending.empty': 'No hay solicitudes pendientes.',
    'apanel.noName': 'Sin nombre',
    'apanel.approve': '✓ Aprobar',
    'apanel.makeAdmin': '★ Hacer admin',
    'apanel.team': 'Voluntarios activos ({n})',
    'apanel.badge.admin': 'admin',
    'apanel.remove': 'Quitar',

    // --- edit person form ---
    'editp.docRequired': 'Ingresa tu cédula (la que usaste al reportar) para editar.',
    'editp.docMismatch': 'Cédula no coincide o no se pudo editar.',
    'editp.field.name': 'Nombre completo',
    'editp.field.doc': 'Cédula / DNI de la persona (opcional)',
    'editp.field.doc.ph': 'V-12345678',
    'editp.field.lastSeen': 'Última ubicación conocida',
    'editp.field.desc': 'Señas (edad, ropa, etc.)',
    'editp.field.contact': 'Tu contacto',
    'editp.field.photo': 'Foto nueva (opcional) — reemplaza la actual',
    'editp.field.editorDoc': 'Tu cédula de reportante (clave para editar)',
    'editp.field.editorDoc.ph': 'La cédula que pusiste al reportar',
    'editp.saving': 'Guardando…',
    'editp.save': 'Guardar cambios',
    'editp.cancel': 'Cancelar',
    'editp.claim': '🙌 Creo que lo encontré',
    'editp.claiming': 'Enviando…',
    'editp.claim.ok': '✅ Avisamos que crees que apareció. Un voluntario lo confirmará.',
    'editp.claim.hint': 'Si ya apareció, avísanos. Un voluntario lo verificará antes de marcarlo como encontrado.',
  },

  en: {
    // --- nav / layout ---
    'nav.report': 'Report',
    'nav.map': 'Map',
    'nav.search': 'Search',
    'nav.safe': "I'm safe",
    'nav.phones': 'Phones',
    'nav.volunteers': 'Volunteers',
    'footer.tagline': 'solidarity project · open data · mutual aid',

    // --- home ---
    'home.kicker': '● Emergency response',
    'home.title': 'When every minute counts,\nhelp arrives faster.',
    'home.lead': 'Report an emergency with your location, find your loved ones, and coordinate the rescue. Works even on a weak signal.',
    'home.cta': '🆘 Get help now',
    'home.card.map.title': 'SOS map',
    'home.card.map.desc': 'Volunteers and rescuers see where help is needed, live.',
    'home.card.search.title': 'Find people',
    'home.card.search.desc': 'Search for or report someone missing after the quake.',
    'home.card.safe.title': "I'm safe",
    'home.card.safe.desc': 'Let your family know you are safe in seconds.',
    'home.card.sos.title': 'Report SOS',
    'home.card.sos.desc': 'Medical, rescue, trapped, water or food.',
    'home.card.phones.title': 'Emergency phones',
    'home.card.phones.desc': 'Firefighters, ambulances and rescue. Tap to call.',

    // --- tipos de emergencia ---
    'type.medical': '🩺 Medical / injured',
    'type.rescue': '🚒 Rescue',
    'type.trapped': '🏚️ Trapped / collapse',
    'type.water_food': '💧 Water / food',
    'type.other': '❓ Other',
    'type.medical.short': '🩺 Medical',
    'type.rescue.short': '🚒 Rescue',
    'type.trapped.short': '🏚️ Trapped',
    'type.water_food.short': '💧 Water/food',
    'type.other.short': '❓ Other',

    // --- estados ---
    'status.pending': 'pending',
    'status.dispatched': 'on the way',
    'status.resolved': 'resolved',
    'status.false_report': 'discarded',
    'status.pending.long': 'Pending — waiting for help',
    'status.dispatched.long': 'On the way — help is coming',
    'status.resolved.long': 'Resolved — attended',
    'status.false_report.long': 'Discarded',

    // --- SOS ---
    'sos.kicker': '● Emergency',
    'sos.title': 'Get help',
    'sos.lead': 'Your report will appear on the map so volunteers and rescuers can find you.',
    'sos.queued.count': '⏳ {n} report(s) saved offline. They will be sent when the network returns.',
    'sos.field.type': 'Type of emergency',
    'sos.field.what': "What's happening? (how many people, injuries, details)",
    'sos.field.what.ph': 'E.g.: 4 people trapped on the ground floor, one injured.',
    'sos.field.contact': 'Contact (optional)',
    'sos.field.contact.ph': 'Name and/or phone',
    'sos.loc.title': '📍 Location',
    'sos.loc.coords': 'Lat {lat}, Lng {lng}',
    'sos.loc.getting': 'Getting location…',
    'sos.loc.useGps': 'Use my GPS location',
    'sos.loc.manual': 'Where are you? (written reference)',
    'sos.loc.manual.ph': 'E.g.: Bolívar Ave., blue building across from the plaza, 3rd floor.',
    'sos.err.noGps': "We couldn't get your GPS location. You can write a reference and send anyway.",
    'sos.err.noLocAtAll': 'Share your GPS location or write a reference of where you are.',
    'sos.err.noSupport': "Your device doesn't support geolocation.",
    'sos.err.captcha': 'Complete the anti-spam check to send.',
    'sos.submit': 'Send SOS',
    'sos.submitting': 'Sending…',
    'sos.err.generic': "Couldn't send. Please try again.",
    'sos.ok': '✅ SOS sent. Stay safe, help is on the way.',
    'sos.queued': '⏳ Offline: your SOS was saved and will be sent automatically.',
    'sos.ref.prefix': '📍 Reference',
    'sos.share.title': 'Share this link with your family so they can follow the status:',
    'sos.share.copy': '📋 Copy link',
    'sos.share.copied': '✓ Copied',
    'sos.share.whatsapp': '💬 WhatsApp',
    'sos.share.waText': 'Follow my SOS: {url}',

    // --- mapa ---
    'map.kicker': '● Live coordination',
    'map.title': 'SOS map',
    'map.lead': 'Reports appear in real time. Volunteers: coordinate by area and priority.',
    'map.legend.pending': 'Pending',
    'map.legend.dispatched': 'On the way',
    'map.legend.resolved': 'Resolved',
    'map.filter.all': 'All ({n})',
    'map.loading': 'Loading map…',
    'map.error': "⚠️ We couldn't load the map. Retrying…",
    'map.noCoords': "{n} report(s) without GPS don't appear on the map (see volunteer list).",
    'map.noDesc': 'No description',

    // --- buscar ---
    'search.kicker': '● People',
    'search.title': 'Find people',
    'search.lead': 'Search by name or report someone missing.',
    'search.input.ph': 'Name or ID…',
    'search.btn': 'Search',
    'search.report.open': '➕ Report missing person',
    'search.report.close': 'Close',
    'search.field.name': 'Full name',
    'search.field.doc': 'ID / passport (optional)',
    'search.field.doc.ph': 'V-12345678',
    'search.field.lastSeen': 'Last known location',
    'search.field.desc': 'Description (age, clothing, etc.)',
    'search.field.contact': 'Your contact',
    'search.field.editorDoc': 'Your reporter ID (optional) — needed to edit later',
    'search.field.editorDoc.ph': 'Your ID, e.g. V-12345678',
    'search.field.photo': 'Photo (optional) — helps identify',
    'search.photo.preview': 'Preview',
    'search.submit': 'Report',
    'search.uploading': 'Uploading photo…',
    'search.ok': '✅ Report registered.',
    'search.queued': '⏳ Offline: it will be sent when the network returns.',
    'search.err.captcha': 'Complete the anti-spam check to send.',
    'search.noResults': 'No results.',
    'search.edit': '✏️ Edit',
    'person.status.missing': 'missing',
    'person.status.safe': 'safe',
    'person.status.found': 'found',
    'person.status.found_pending': 'to confirm',

    // --- estoy bien ---
    'safe.kicker': '● Safe',
    'safe.title': "I'm safe",
    'safe.lead': 'Let others know you are safe. You will show as “safe” when someone searches for you.',
    'safe.field.name': 'Your full name',
    'safe.field.doc': 'ID / passport (optional) — lets you edit later',
    'safe.field.doc.ph': 'V-12345678',
    'safe.field.where': 'Where are you? (shelter, area)',
    'safe.field.contact': 'Contact (optional)',
    'safe.field.photo': 'Photo (optional) — helps people recognize you',
    'safe.submit': "Let them know I'm safe",
    'safe.uploading': 'Uploading photo…',
    'safe.ok': '✅ Registered. Your loved ones will be able to find you.',
    'safe.queued': '⏳ Offline: it will be sent when the network returns.',
    'safe.err.captcha': 'Complete the anti-spam check to send.',
    'safe.reportedBy': 'the person themselves',

    // --- emergencias ---
    'emerg.kicker': '● Directory',
    'emerg.title': 'Emergency numbers',
    'emerg.lead': 'Tap a number to call directly. If you can geolocate the emergency, report it on the map too.',
    'emerg.national': 'National',
    'emerg.rescue': 'Rescue and ambulances',
    'emerg.outdated': 'Is a number from your area missing or changed? Let us know to keep it updated.',

    // --- seguimiento /r/[id] ---
    'track.kicker': '● SOS tracking',
    'track.loading': 'Loading tracking…',
    'track.notfound.title': 'Report not found',
    'track.notfound.lead': "This link doesn't match any active report. It may have been resolved and archived, or the link may be copied incorrectly.",
    'track.notfound.home': 'Go home',
    'track.reportedAt': 'Reported on {date}',
    'track.autoUpdate': 'This page updates by itself. Keep it open to see the status live.',
    'track.viewMap': 'View map',
    'track.reportAnother': 'Report another SOS',

    // --- voluntarios (login/guard) ---
    'vol.kicker': '● Volunteers',
    'vol.title': 'Coordination panel',
    'vol.loading': 'Loading…',
    'vol.access.kicker': '● Volunteer access',
    'vol.access.lead': 'Access for authorized volunteers only. Sign in with your Google account.',
    'vol.google': 'Continue with Google',
    'vol.noperm.kicker': '● Restricted access',
    'vol.noperm.title': 'No permission',
    'vol.noperm.lead': 'Your account ({email}) is not authorized as a volunteer. Contact a coordinator to be added.',
    'vol.signout': 'Sign out',

    // --- admin ---
    'admin.kicker': '● Administration',
    'admin.title': 'Volunteer management',
    'admin.loading': 'Loading…',
    'admin.norole.title': 'Restricted access',
    'admin.norole.lead': 'Sign in from the volunteer panel.',
    'admin.goVol': 'Go to volunteers',
    'admin.noperm.title': 'No permission',
    'admin.noperm.lead': 'Your account ({email}) is not an administrator. This section is for coordinators only.',
    'admin.backReports': '← Reports panel',
    'admin.lead': 'Approve requests and manage the volunteer team.',

    // --- volunteer panel ---
    'vpanel.kicker': '● Coordination',
    'vpanel.title': 'Volunteer panel',
    'vpanel.admin': '★ Volunteer management',
    'vpanel.signout': 'Sign out ({email})',
    'vpanel.summary': '{pending} pending · {dispatched} on the way · {resolved} resolved',
    'vpanel.filter.active': 'Active',
    'vpanel.filter.pending': 'Pending',
    'vpanel.filter.dispatched': 'On the way',
    'vpanel.filter.resolved': 'Resolved',
    'vpanel.filter.false_report': 'False',
    'vpanel.loading': 'Loading reports…',
    'vpanel.empty': 'No reports in this view.',
    'vpanel.viewMap': 'view map',
    'vpanel.noGps': '📍 No GPS — see reference in the description',
    'vpanel.action.dispatch': '→ On the way',
    'vpanel.action.resolve': '✓ Resolved',
    'vpanel.action.reopen': '↺ Reopen',
    'vpanel.action.false': '⚑ False',
    'vpanel.tab.reports': 'SOS reports',
    'vpanel.tab.persons': 'People',

    // --- confirmations (modals) ---
    'confirm.cancel': 'Cancel',
    'confirm.report.false.title': 'Mark as false report?',
    'confirm.report.false.msg': "It will disappear from the public map. You can reopen it later.",
    'confirm.report.false.ok': 'Yes, mark as false',
    'confirm.report.resolve.title': 'Mark as resolved?',
    'confirm.report.resolve.msg': 'It will show as attended on the map.',
    'confirm.report.resolve.ok': 'Yes, resolved',
    'confirm.person.found.title': 'Confirm the person was found?',
    'confirm.person.found.msg': "It will be marked as found. Make sure you've verified it.",
    'confirm.person.found.ok': 'Yes, found',
    'confirm.person.reject.title': 'Reject the appearance report?',
    'confirm.person.reject.msg': 'It will be marked as missing again.',
    'confirm.person.reject.ok': 'Yes, still missing',
    'confirm.person.safe.title': 'Mark as safe?',
    'confirm.person.safe.msg': 'It will show as safe.',
    'confirm.person.safe.ok': 'Yes, safe',
    'confirm.claim.title': 'Report that you think they appeared?',
    'confirm.claim.msg': 'A volunteer will verify before marking them as found.',
    'confirm.claim.ok': 'Yes, report it',

    // --- persons panel (volunteers) ---
    'ppanel.summary': '{missing} missing · {safe} safe · {found} found',
    'ppanel.filter.all': 'All',
    'ppanel.filter.missing': 'Missing',
    'ppanel.filter.safe': 'Safe',
    'ppanel.filter.found': 'Found',
    'ppanel.filter.found_pending': 'To confirm',
    'ppanel.loading': 'Loading people…',
    'ppanel.empty': 'No people in this view.',
    'ppanel.reportedBy': 'Reported by: {who}',
    'ppanel.claimNote': '🙌 The reporter thinks they appeared. Confirm or reject.',
    'ppanel.action.missing': '🔎 Missing',
    'ppanel.action.safe': '✅ Safe',
    'ppanel.action.found': '🙌 Found',
    'ppanel.action.confirmFound': '✓ Confirm found',
    'ppanel.action.reject': '✗ Not found',

    // --- admin panel ---
    'apanel.pending': 'Pending requests',
    'apanel.pending.count': 'Pending requests ({n})',
    'apanel.loading': 'Loading…',
    'apanel.pending.empty': 'No pending requests.',
    'apanel.noName': 'No name',
    'apanel.approve': '✓ Approve',
    'apanel.makeAdmin': '★ Make admin',
    'apanel.team': 'Active volunteers ({n})',
    'apanel.badge.admin': 'admin',
    'apanel.remove': 'Remove',

    // --- edit person form ---
    'editp.docRequired': 'Enter your ID (the one you used when reporting) to edit.',
    'editp.docMismatch': "ID doesn't match or the edit couldn't be saved.",
    'editp.field.name': 'Full name',
    'editp.field.doc': "Person's ID / passport (optional)",
    'editp.field.doc.ph': 'V-12345678',
    'editp.field.lastSeen': 'Last known location',
    'editp.field.desc': 'Description (age, clothing, etc.)',
    'editp.field.contact': 'Your contact',
    'editp.field.photo': 'New photo (optional) — replaces the current one',
    'editp.field.editorDoc': 'Your reporter ID (key to edit)',
    'editp.field.editorDoc.ph': 'The ID you entered when reporting',
    'editp.saving': 'Saving…',
    'editp.save': 'Save changes',
    'editp.cancel': 'Cancel',
    'editp.claim': '🙌 I think I found them',
    'editp.claiming': 'Sending…',
    'editp.claim.ok': "✅ We've flagged that you think they appeared. A volunteer will confirm it.",
    'editp.claim.hint': 'If they have appeared, let us know. A volunteer will verify before marking them as found.',
  },
} as const;

export type DictKey = keyof typeof dict.es;
